--- 
title: "A gentle Introduction of Coding with R"
author: "Masumbuko Semba"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: dege.bib
biblio-style: apalike
link-citations: yes
description: " Learning to code with R is a new literacy of the fast changing world. The book will takes you through the basic of learning R while unlearning other languages."
---

# Preface {-}
We live in an age where data generated and collected in a fraction of a minute is enormous. To get insight out of these data they must analysed. Several tools have been developed to tacke the issue of data and obtain knowledge out of this digital data age. One of the tools is the R programming language, which has increased recently and become a one-stop solution to data problem.

In this book, I introduce to the readers some of the useful packages and tools in R that are  commonly used to handle and tranform data and produce elegant graphics with R programming language. The book talks about coding using R programming languages. Coding is nothing more than telling a computer what to do in a language the computer understands. Learning to code will help you to develop critical thinking skills and ability to solve problems. We will cover various analytical processes and methods that will help reader to apply them to analyse their own datasets.

# Prerequisities {-}
I developed this book with a focus to readers who are unfamiliar with statistical analysis and coding. I tried to make it as simple as posssible to provide the background of underlaying statistics to provide a glimpse of the theory behind statistical concepts. Because the book use R, I will take through each step in R so that the reader get familiar with this powerful programming language. 

> --- Masumbuko Semba



# Resources {-}
Here is a list of resources that make you up and running in R. I will keep adding the list whenever I find a resourceful document floating online.

1. [A Sufficient Introduction to R](https://dereksonderegger.github.io/570L/4-data-types.html)
2. [UC Business Analytics R Programming Guide](http://uc-r.github.io/)
3. [graphics with ggplot2](https://r4stats.com/examples/graphics-ggplot2/)
4. [ggplot graphics](https://www.statmethods.net/advgraphs/ggplot2.html)
5. [Beautiful plotting in R with ggplot2](file:///E:/R2018/Beautiful%20plotting%20in%20R%20%20A%20ggplot2%20cheatsheet.html)
6. [The definitive guide of Rmarkdown](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html)
7. [bookdownplus](https://bookdown.org/baydap/bookdownplus/academic.html#articles)